### ISSUE TITLE
What is the difference with GetX?

### ISSUE THREAD

**Issue by bubnenkoff** [RafaelBarbosatec/cube#49]
subj

**Comment by RafaelBarbosatec** [comment]
Hi @bubnenkoff !
So, there are a few differences:
- Cube uses ChangeNotifier instead of Stream. This makes things much simpler and changes are reflected immediately.
- Cubes use dependency injection using [get_It](https://pub.dev/packages/get_it);
- Cubes provider a way to communication with View called `CubeAction`. That way you can delegate View inherent actions that depend on the BuildContext such as navigation, animations, etc.
- Cubes uses extensions to create Widget listening a`ObservableValue` in simple way.
- Cubes have widgets that facilitate reactive use with `ObservableValue` like `CFeedBackManager`, `CTextFormField `, `CAnimatedList`.

I think that's it. ☺️
I hope I helped you.
